language: node_js
node_js:
- '0.12'
sudo: required
dist: precise
group: edge
env:
  global:
  - CF_APP=deployment-tracker
  - CF_API=https://api.ng.bluemix.net
  - CF_ORGANIZATION=Watson-Data-Lab 
  - CF_SPACE=metrics
  - secure: VJ0JkhCnEMhhOEUiJzS2zwdjzz9d9o6Rn5KeTMoF1l9EltM3JsYZgRQ/oS3UO/A21jf62rPFpRvsLH1yWIPwaTjiqmWRQWQYPyAB6ekzpohGow245t09KJmnxEdqdRC/LjWCIn+n8awpV01A2rKtErnlJWVzeDK5WfLBaXUvOoc=
  - secure: PzksGxTfTQmE85IYapCHAeFlrMKhiKugSEZCAUNfNavUPPt1fq690QEoN5p5vzA2IywK0h6hmJdnSoYKu8qbTx7YCHRedgIUqSMfBMrehVqU1jtpZIvGslar3g2g3tMEZAt4O+hQZnpl8SoYIljkHV0PuhE+XJ7lElT4Jt9HnUw=
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script: cf-blue-green-travis
  on:
    branch: migration-test
    repo: IBM-Bluemix/cf-deployment-tracker-service
    
